const ejs = require('ejs');
const path = require('path');

const templatePath = path.resolve(__dirname, '../templates/index.ejs');
const vapidPublicKey = process.env.VAPID_PUBLIC_KEY;

/**
* Serves the main page for registering a user to a device's notifications.
* Uses a one time password generated by the device.
* @param {string} deviceId device id
* @param {string} otp one time password
* @returns {buffer}
*/
module.exports = (deviceId, otp, context, callback) => {
  render(null, deviceId, otp, context, callback);
};

function render(err, deviceId, otp, context, callback) {
  return ejs.renderFile(
    templatePath,
    {
      error: err ? err.message : '',
      deviceId,
      vapidPublicKey,
      otp,
      env: context.service.environment,
    },
    {},
    (e, response) => callback(e, Buffer.from(response || ''), { 'Content-Type': 'text/html' })
  );
}
